version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pat@2022
    ports:
      - 15432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
