/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.40.150 (chou_test_测试机_主)
 Source Server Type    : PostgreSQL
 Source Server Version : 130002
 Source Host           : 192.168.40.150:5432
 Source Catalog        : pat
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130002
 File Encoding         : 65001

 Date: 25/04/2021 13:36:55
*/


-- ----------------------------
-- Table structure for pat_config
-- ----------------------------
DROP TABLE IF EXISTS "public"."pat_config";
CREATE TABLE "public"."pat_config" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
),
  "config_name" varchar(64) COLLATE "pg_catalog"."default",
  "config_code" varchar(64) COLLATE "pg_catalog"."default",
  "config_value" varchar(255) COLLATE "pg_catalog"."default",
  "remark" varchar(255) COLLATE "pg_catalog"."default",
  "seq_no" int4,
  "parent_id" int8,
  CONSTRAINT "pat_config_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "pat_config_unique" UNIQUE ("config_code", "config_value", "parent_id")
)
;

ALTER TABLE "public"."pat_config"
  OWNER TO "postgres";

COMMENT ON COLUMN "public"."pat_config"."config_name" IS '配置名称';

COMMENT ON COLUMN "public"."pat_config"."config_code" IS '配置code';

COMMENT ON COLUMN "public"."pat_config"."config_value" IS '配置值';

COMMENT ON COLUMN "public"."pat_config"."remark" IS '备注';

COMMENT ON COLUMN "public"."pat_config"."seq_no" IS '序列';

COMMENT ON COLUMN "public"."pat_config"."parent_id" IS '父id';

COMMENT ON TABLE "public"."pat_config" IS 'pat 配置表';
