/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.40.254 ES docker
 Source Server Type    : PostgreSQL
 Source Server Version : 140002
 Source Host           : 192.168.40.254:15432
 Source Catalog        : poetry
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140002
 File Encoding         : 65001

 Date: 01/04/2022 15:58:09
*/


-- ----------------------------
-- Table structure for pat_resource
-- ----------------------------
DROP TABLE IF EXISTS "pat_resource";
CREATE TABLE "pat_resource" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "uri" varchar(255) COLLATE "pg_catalog"."default",
  "uri_desc" varchar(255) COLLATE "pg_catalog"."default",
  "index" int4,
  "role" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "pat_resource"."uri" IS '资源uri';
COMMENT ON COLUMN "pat_resource"."uri_desc" IS '资源描述';
COMMENT ON COLUMN "pat_resource"."index" IS '序号';
COMMENT ON COLUMN "pat_resource"."role" IS '多个以, 分隔';

-- ----------------------------
-- Records of pat_resource
-- ----------------------------
BEGIN;
INSERT INTO "pat_resource" VALUES (1, '/api/test_0', '测试', 0, 'USER2');
COMMIT;

-- ----------------------------
-- Table structure for pat_user
-- ----------------------------
DROP TABLE IF EXISTS "pat_user";
CREATE TABLE "pat_user" (
  "id" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "sign_up" varchar(128) COLLATE "pg_catalog"."default",
  "nick_name" varchar(128) COLLATE "pg_catalog"."default",
  "status" char(1) COLLATE "pg_catalog"."default",
  "password" varchar(255) COLLATE "pg_catalog"."default",
  "pwd_fail_count" int4,
  "login_ts" timestamptz(6),
  "role" varchar(255) COLLATE "pg_catalog"."default",
  "create_ts" timestamptz(6),
  "update_ts" timestamptz(6),
  "user_name" varchar(64) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "pat_user"."sign_up" IS '注册方式 0 邮箱  1 手机号';
COMMENT ON COLUMN "pat_user"."nick_name" IS '昵称';
COMMENT ON COLUMN "pat_user"."status" IS '0 待核验验证码 1 验证码成功   2 实名认证成功（需要相关验证码）';
COMMENT ON COLUMN "pat_user"."password" IS '密码 内置盐';
COMMENT ON COLUMN "pat_user"."pwd_fail_count" IS '密码登录失败次数 超过一定数时冻结  待验证码登录解冻';
COMMENT ON COLUMN "pat_user"."login_ts" IS '最新登录时间，当长时间未登录只能用验证码形式登录';
COMMENT ON COLUMN "pat_user"."role" IS '多个角色,以","分隔 角色常量 详见PatRoleConstant';
COMMENT ON COLUMN "pat_user"."create_ts" IS '创建时间';
COMMENT ON COLUMN "pat_user"."update_ts" IS '更新时间';
COMMENT ON COLUMN "pat_user"."user_name" IS '用户名称';

-- ----------------------------
-- Records of pat_user
-- ----------------------------
BEGIN;
INSERT INTO "pat_user" VALUES ('test_id', '0', 'test', '1', '$2a$10$1LUDG1rAnA.DtRdxpJIkMugrJsL6LljVMVxQ.B9v59373El62AXDS', 0, '2022-03-31 14:55:15+00', 'USER', '2022-03-31 14:55:27+00', '2022-03-31 14:55:30+00', 'test');
COMMIT;

-- ----------------------------
-- Uniques structure for table pat_resource
-- ----------------------------
ALTER TABLE "pat_resource" ADD CONSTRAINT "pat_resource_uq_0" UNIQUE ("uri");

-- ----------------------------
-- Primary Key structure for table pat_resource
-- ----------------------------
ALTER TABLE "pat_resource" ADD CONSTRAINT "pat_resource_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table pat_user
-- ----------------------------
ALTER TABLE "pat_user" ADD CONSTRAINT "pat_user_pkey" PRIMARY KEY ("id");
