server:
  port: 18080

spring:
#  main:
#    web-application-type: none  # 无端口模式启动web项目
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null

  elasticsearch:
    rest:
      uris: ["192.168.40.254:19201"]
      username: elastic
      password: w12345

  datasource:
    url: jdbc:postgresql://192.168.40.254:15432/poetry
    password: pat@2022

  redis:
    host: 192.168.40.254
    password: ad05m_in21zrd9518

