server:
  port: 18080

spring:
#  main:
#    web-application-type: none  # 无端口模式启动web项目
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null

  elasticsearch:
    rest:
      uris: ["192.168.40.254:19201"]
      username: elastic
      password: w12345

  datasource:
    url: jdbc:postgresql://192.168.40.254:15432/poetry
    password: pat@2022

  redis:
    host: 192.168.40.254
    port: 16379
    password: "poet-redis@2022"

app:
  oauth:
    client:
      enabled: true
      resource_id: poetry-service
      oauth_url: http://127.0.0.1:18081/oauth/token
      oauth_token: grant_type=authorization_code&client_id=poetry-web-dev&client_secret=test&redirect_uri=http://127.0.0.1:8080&code=%s
      oauth_refresh_token: grant_type=refresh_token&client_id=poetry-web-dev&client_secret=test&scope=server&refresh_token=%s