spring:
  profiles:
    active:
      on-profile:
        - dev

  datasource:
    url: jdbc:postgresql://192.168.40.254:15432/poetry
    password: pat@2022

app:
  code-generate:
    base-dir:  D:\amuse\workplace\chouway\chouway\pat-frame\pat-app\pat-poetry
    base-project: pat-poetry-api